spring:
  management:
    endpoints:
      web:
        exposure:
          include: health,mappings
        base-path: /actuator
    security:
      enabled: false

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:Billink}?createDatabaseIfNotExist=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Ricardo55010}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
  application:
    name: consumer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9001
